name: Merge Pull Request actions
on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: CocoaPod Install
        run: pod install
      
      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: Run Fastlane for iOS - Upload to App Center
        env:
            GIT_AUTHORIZATION: ${{ secrets.GIT_AUTHORIZATION }}
        run: bundle exec fastlane ios dev_appCenter