name: Merge Pull Request actions
on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: CocoaPod Install
        run: pod install
      
      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: Run Fastlane for iOS - Upload to App Center
        env:
            GIT_AUTHORIZATION: ${{ secrets.GIT_AUTHORIZATION }}
            BUNDLE_IDENTIFIER: ${{ secrets.BUNDLE_IDENTIFIER }}
            ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
            DEVELOPER_PORTAL_TEAM_ID: ${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}
            TEMP_KEYCHAIN_USER: ${{ secrets.TEMP_KEYCHAIN_USER }}
            TEMP_KEYCHAIN_PASSWORD: ${{ secrets.TEMP_KEYCHAIN_PASSWORD }}
            FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
            MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
            APP_CENTER_API_KEY: ${{ secrets.APP_CENTER_API_KEY }}
            APP_CENTER_API_TOKEN: ${{ secrets.APP_CENTER_API_TOKEN }}


        run: bundle exec fastlane ios dev_appCenter